name: 'Create TS compiler reproductions in an issue'
description: 'Does what it says on the tin'
author: 'Microsoft'
inputs:
  github-token:
    description: 'API token for GitHub requests'
    required: true

  label:
    required: false
    description: 'What label should be on an issue to indicate it has a repro?'
    default: 'Has Repro'

  repo:
    required: false
    description: 'What repo should this action look at, if not set it uses the same repo'

  code-tag:
    required: false
    description: 'What tag should be applied to the markdown code block?'
    default: 'repro'

  issue:
    required: false
    description: 'Limits analysis to a single issue'

  bisect:
    required: false
    description: 'Runs a git bisect on an existing repro. Requires `issue` to be set. Value can be revision labels (e.g. `good v4.7.3 bad main`) or `true` to infer bisect range.'

runs:
  using: 'node16'
  main: 'dist/index.js'
